export const DEFAULT_CV_RULES = [
  "Act as a senior recruiter. Prioritize role-fit evidence, impact clarity, and ATS keyword alignment for the target role.",
  "Rewrite summary to align with JD responsibilities while preserving the base summary length (+/-10% chars) and sentence count.",
  "Bold important JD-aligned technical keywords in summary using markdown **keyword** format.",
  "When using markdown bold, keep markers clean: use **keyword** (no leading/trailing spaces inside ** **).",
  "Do not add claims beyond the base resume experience. Keep every statement grounded in provided resume context.",
  "Return latestExperience.bullets as the COMPLETE final bullet list for the latest experience block (full ordered output, not delta).",
  "Reorder latest experience bullets to mirror JD responsibilities order.",
  "Do not rewrite or paraphrase any existing latest experience bullet; preserve original text verbatim and only change order.",
  "When top-3 JD responsibility gaps exist, add 2-3 new bullets (max 3) grounded in base context; if no direct exposure exists, use truthful transferable experience + willingness-to-learn phrasing.",
  "Prefer placing newly added bullets before reordered base bullets in the same responsibility order they address.",
  "Before final output, self-check: (1) all base bullets are preserved verbatim, (2) any additions are grounded, (3) output remains concise and role-relevant.",
  "Keep every latest experience bullet grounded in base resume facts and technologies; no fabricated scope, systems, or outcomes.",
  "Any new bullet must follow Google XYZ style: achieved X by doing Y, resulting in Z (or equivalent qualitative outcome).",
  "For newly added bullets, avoid reusing the same primary tech stack already emphasized in existing latest-experience bullets; prioritize complementary JD-required skills not yet covered.",
  "Do not invent numeric metrics. If metrics are unavailable, use truthful qualitative outcomes (scope, speed, reliability, quality, or stakeholder impact).",
  "Keep any new bullet similar in length to nearby bullets (+/-20%) and consistent with the resume tone.",
  "For every newly added bullet, bold at least one JD-critical keyword using markdown **keyword** format.",
  "For every newly added bullet, keep markdown bold markers syntactically clean (valid: **keyword**, invalid: **keyword ** or ** keyword**).",
  "Return skillsFinal as the COMPLETE final skills list (not delta), with max 5 major categories.",
  "Prioritize JD must-have technologies in skillsFinal for ATS matching when grounded in base resume context.",
  "If a JD must-have has no grounded evidence in base resume context, use the closest truthful transferable skill and never fabricate direct ownership.",
  "You may add missing JD-critical skills and freely re-group/re-order categories/items while preserving important base skills.",
  "Keep skills plausible and role-consistent; avoid fabricated project claims or impossible seniority signals.",
  "Order skillsFinal by JD relevance priority (most important categories/items first) and keep category count <= 5.",
  "Do not return skillsAdditions; return skillsFinal only.",
  "Resume target output keys allowed: cvSummary, latestExperience, skillsFinal only.",
  "Prefer concrete, ATS-safe phrasing. Avoid hype, fluff, or repeated adjectives.",
];

export const DEFAULT_COVER_RULES = [
  "Return output under cover object only.",
  "Use three semantic sections mapped to paragraphOne/paragraphTwo/paragraphThree (not necessarily short).",
  "Each section should be substantial, natural, and specific; avoid one-line generic statements.",
  "Include and populate these fields when possible: candidateTitle, subject, date, salutation, closing, signatureName.",
  "candidateTitle should align with the JD role title (not a fixed generic title).",
  "Subject should be concise and role-focused (prefer 'Application for <Role>'); do not append candidate name.",
  "Salutation should contain addressee text only (no leading 'Dear', no trailing comma).",
  "Paragraph 1 (Application intent): state target role and role-fit positioning based on real resume context.",
  "Paragraph 2 (Evidence mapping): map experience to JD responsibilities in priority order, using concrete evidence and delivery outcomes.",
  "Paragraph 2 must cover the top JD responsibilities first; if direct exposure is missing, use truthful transferable evidence + explicit willingness to learn.",
  "Paragraph 3 (Motivation): explain why this role/company is attractive in a specific, non-generic way linked to JD context.",
  "Naturally bold JD-critical terms in cover paragraphs using clean markdown **keyword** markers.",
  "Keep markdown bold markers clean: **keyword** (no spaces inside markers).",
  "Write as a strong candidate narrative (clear, confident, specific), not recruiter boilerplate.",
  "Do not fabricate employers, tools, projects, metrics, or domain exposure.",
  "Write in natural first-person candidate voice (not recruiter voice, not AI-generic tone).",
  "Keep language application-ready with concrete wording, not hype or filler.",
  "Cover target output keys allowed: cover only.",
];
