export const DEFAULT_CV_RULES = [
  "Act as a senior recruiter. Prioritize role-fit evidence, impact clarity, and ATS keyword alignment for the target role.",
  "Rewrite summary to align with JD responsibilities while preserving the base summary length (+/-10% chars) and sentence count.",
  "Bold important JD-aligned technical keywords in summary using markdown **keyword** format.",
  "When using markdown bold, keep markers clean: use **keyword** (no leading/trailing spaces inside ** **).",
  "Do not add claims beyond the base resume experience. Keep every statement grounded in provided resume context.",
  "Return latestExperience.bullets as the COMPLETE final bullet list for the latest experience block (full ordered output, not delta).",
  "Reorder latest experience bullets to mirror JD responsibilities order.",
  "Do not rewrite or paraphrase any existing latest experience bullet; preserve original text verbatim and only change order.",
  "When clear JD gaps exist and evidence exists in base context, you may add up to 3 new bullets; if no grounded evidence exists, do not fabricate additions.",
  "Prefer placing newly added bullets before reordered base bullets in the same responsibility order they address.",
  "Before final output, self-check: (1) all base bullets are preserved verbatim, (2) any additions are grounded, (3) output remains concise and role-relevant.",
  "Keep every latest experience bullet grounded in base resume facts and technologies; no fabricated scope, systems, or outcomes.",
  "Any new bullet must follow Google XYZ style: achieved X by doing Y, resulting in Z (or equivalent qualitative outcome).",
  "Do not invent numeric metrics. If metrics are unavailable, use truthful qualitative outcomes (scope, speed, reliability, quality, or stakeholder impact).",
  "Keep any new bullet similar in length to nearby bullets (+/-20%) and consistent with the resume tone.",
  "For every newly added bullet, bold 1-3 JD-critical keywords using markdown **keyword** format.",
  "Return skillsFinal as the COMPLETE final skills list (not delta), with max 5 major categories.",
  "Ensure skillsFinal covers all JD must-have/required technologies and tools (prefer exact JD terms for ATS matching).",
  "You may add missing JD-critical skills and freely re-group/re-order categories/items while preserving important base skills.",
  "Keep skills plausible and role-consistent; avoid fabricated project claims or impossible seniority signals.",
  "Order skillsFinal by JD relevance priority (most important categories/items first) and keep category count <= 5.",
  "Do not return skillsAdditions; return skillsFinal only.",
  "Prefer concrete, ATS-safe phrasing. Avoid hype, fluff, or repeated adjectives.",
];

export const DEFAULT_COVER_RULES = [
  "Generate exactly three short paragraphs (no extra lines).",
  "Return output under cover object only.",
  "Include optional fields when available: subject, date, salutation, closing, signatureName.",
  "Paragraph 1: state the role being applied for.",
  "Paragraph 2: map the candidate's experience to the top JD responsibilities with concrete evidence from the resume only.",
  "Paragraph 3: explain why the candidate is interested in the company and role using the company name.",
  "If company-specific context is missing, use role-and-mission motivation without inventing facts.",
  "Avoid exaggerated tone, repetition, and generic filler.",
  "Keep wording recruiter-friendly, specific, and application-ready.",
];
